laminas/technical-steering-committee

meetings/agenda.md
* TSC Members - inclusion / exclusion
* Financing
* Full-time employed Maintainers
* LTS strategy - Should Laminas provide LTS releases or not?
* PHP Version bump strategy
* MVC Support - Active Development?
* Roadmap for components
* Doctrine integration
=> First TSC Meeting: items to discuss

meetings/agenda.md
* Major release community guideline
* Breaking change review and approval process
* Time constraints between major releases
* What should be considered a minimal change to warrant major release
* Soft upper time limit for how long major release can be postponed to wait
for more major targeting features to be completed
* Overall stance on breaking non-feature changes aimed at improving code and
design quality. Signature changes, adoption of new language features.
* Feature deprecation and removal timeframe
=> First TSC meeting: major releases guideline

meetings/agenda.md
> * CLI tooling for Laminas MVC, Mezzio, components
> * Full example / demo applications
>   * developed under https://github.com/laminas-tutorials
>   * follows best practices and implements typical features
>   * basis for new tutorials
=> Adds CLI tooling and example application to April 2020 agenda

meetings/agenda.md
I've spoken to Abdul Malik Ikhsan, and he is interested in being a TSC member. We should vote during the next TSC meeting.
=> Nominating @samsonasik for TSC

meetings/agenda.md
He has been a long-time contributor to the framework, and frequently provides patches and reviews.
=> Nomination: Witold Wasiczko

meetings/agenda.md
Per the suggestion of @Ocramius
=> Nomination: Luis Cobucci

meetings/agenda.md
Max has been a regular and steady contributor to Expressive/Mezzio, as well as a number of components, and has a good eye for quality.
=> Nomination: Maximilian Bösing

MEMBERS.md
Based on https://github.com/laminas/technical-steering-committee/blob/master/meetings/minutes/2020-04-06-TSC-Minutes.md#new-members
=> update tsc members based on 2020-04-06 meeting

meetings/agenda.md
As already stated on slack and discourse, I would like to talk about the possible future of the laminas-cache library.
=> agenda: future of laminas-cache

meetings/agenda.md
I've fielded questions both from people who want to be listed as support providers, as well as those looking for commercial support offerings, and would like to discuss the idea during the next meeting.
=> Adds agenda item asking about listing support providers

meetings/agenda.md
Matthew Setter is a software engineer, technical writer and podcaster. He is a long time community member, occasional contributor, author of the [Master Zend Framework](https://masterzendframework.com) website and author of the [Zend Expressive Essentials](https://masterzendframework.com/zend-expressive-essentials/) book (that is now being updated to Mezzio Essentials).
He is a passionate person which leads him to seek new things to explore; it might make him not ideal candidate for a maintainer role with the boring routine tasks, but, combined with the excellence at technical writing, makes him a good candidate for the TSC.
=> Nominate Matthew Setter

meetings/agenda.md, meetings/minutes/2020-05-04-TSC-Minutes.md
This patch includes the meeting minutes, as well as updates to the
agenda to set the date for next month's meeting, and retain the items
that remained undiscussed from this month's meeting.
=> Meeting minutes from 2020-05-04 TSC meeting

meetings/agenda.md
I'd like to talk about a possible release cycle for laminas/mezzio packages.
=> agenda: laminas/mezzio release cycle

MEMBERS.md
=> update tsc member: add Matthew Setter based on meeting at 1 June 2020

meetings/agenda.md
Just a small patch to remove the gender-specific wording (and fix a minor point of grammar) in the agenda.
=> Remove gender-specific terminology from agenda.md

meetings/agenda.md, meetings/minutes/2020-07-06-TSC-Minutes.md
And blank slate for next month's agenda, set for 2020-08-03.
=> Minutes from 2020-07-06 TSC meeting

meetings/agenda.md
- Updates previous item to note who "I" was (in this case, Max).
- Adds item for voting on security-only components.
- Adds item suggesting change in async voting rules.
- Proposes voting on psalm vs phpstan for static analysis
=> Agenda items for August 2020

meetings/agenda.md, meetings/minutes/2020-07-06-TSC-Minutes.md, meetings/minutes/2020-08-03-TSC-Minutes.md
This provides the minutes for the TSC meeting held 2020-08-03, and refreshes the agenda for the next meeting, to be held 2020-09-07.
=> Minutes for the 2020-08-03 TSC meeting

meetings/agenda.md, meetings/minutes/2020-09-07-TSC-Minutes.md
Also resets the agenda for next month.
=> TSC Meeting: 2020-09-07 meeting minutes

meetings/agenda.md
See text contents
| New Feature   | yes
=> Suggest moving RFCs to github issues/PRs

meetings/agenda.md
=> Add agenda item for commercial vendor program update

meetings/agenda.md, meetings/minutes/2020-11-02-TSC-Minutes.md
- Creates minutes for the 2020-11-02 TSC meeting
- Resets the agenda, with the date of the next meeting.
=> Minutes for the 2020-11-02 TSC meeting

meetings/minutes/2020-11-02-TSC-Minutes.md
=> Typo fix: reesarch -> research

meetings/agenda.md
=> Pull request instructions are out of date, referring to master and develop branches which do not exist any more.

.github/ISSUE_TEMPLATE/Maintainer_Nomination.md, MAINTAINERS.md
| BC Break      | yes?
| QA            | yes
As discussed with @weierophinney and the contributors channel, the maintainers guide needs to be updated to the automatic releases workflow.
This PR is just a starting point to drive this document with the technical steering committee to a guide that helps maintainers to maintain the component as intended and have a point of orientation to refer to.
I just incorporated the new process as much as I understood it - which might be off or even totally wrong. So this might also help me and potential other maintainers, who are not part of the steering committee, to better understand the intended process.
=> WIP: Update maintainers guide

meetings/agenda.md, meetings/minutes/2020-12-07-TSC-Minutes.md
Provides minutes from the 2020-12-07 TSC meeting, and updates the agenda (next meeting date still TBD).
=> 2020-12-07 TSC Meeting Minutes

meetings/agenda.md
Proposes we review #61 as part of the next TSC meeting.
=> Propose agenda item for GH actions workflow RFC review

meetings/agenda.md, meetings/minutes/2021-02-01-TSC-Minutes.md
Provides minutes for the 2021-02-01 meeting, and resets the agenda for the next meeting (2021-03-01).
=> Minutes for 2021-02-01 meeting

MEMBERS.md
Having "last updated" not part of the list will remove excess lines between entries.
|    Before          |   After
| ![image](https://user-images.githubusercontent.com/199095/108222401-6cf8f500-7141-11eb-8426-30420b348942.png) | ![image](https://user-images.githubusercontent.com/199095/108222421-74200300-7141-11eb-91b7-dac170f9c0cc.png)
=> Update Members file formatting

meetings/agenda.md
=> Add service-manager-inspector to Agenda

MAINTAINERS.md
=> Downgrade PR to earlier branch: remember to also update the Github base branch

meetings/minutes/2020-11-02-TSC-Minutes.md
| Bugfix        | yes
There was a typo in the meeting minutes. I'd like to fix that.
=> bugfix: fix typo in cache satellite list

meetings/agenda.md
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>
Based on https://github.com/laminas/technical-steering-committee/pull/76#issuecomment-828345143
=> [Agenda] Add laminas-cache-storage-adapter-mongodb to list abandon

meetings/agenda.md
Instead of doing an async vote for the laminas-db nominees, I'm suggesting we do it during the TSC meeting so we can get it over and done with.
=> laminas-db Nominee Votes

meetings/agenda.md, meetings/minutes/2021-05-03-TSC-Minutes.md
Initial draft for the meeting minutes so we can start filling the agenda for 2021-06-07.
=> meeting: minutes for 2021-05-03 meeting, and reset agenda

meetings/agenda.md
This PR contains the same changes as #83
=> Agenda: codestandard 120 chars per line

meetings/agenda.md
This PR contains the same changes as #83
=> Agenda: assert vs Assert

meetings/agenda.md
This PR contains the same changes as #83
=> Agenda: locked dependencies for all php versions

meetings/agenda.md
=> Note that `assert()` should be activated in CI

meetings/agenda.md
Also: updated TSC meeting date
=> Proposed removal of `laminas/laminas-zendframework-bridge` in next minor releases

meetings/agenda.md, meetings/minutes/2021-06-07-TSC-Minutes.md, meetings/minutes/2021-08-02-TSC-Minutes.md
This includes the minutes for the June and August 2021 meetings, and an updated agenda for September 2021.
=> June and August minutes, and September agenda

meetings/agenda.md, meetings/minutes/2021-11-01-TSC-Minutes.md
- Provides minutes for the 2021-11-01 meeting
- Resets the agenda for the 2021-12-06 meeting
=> Minutes for 2021-11-01 TSC meeting

meetings/agenda.md
Signed-off-by: ZVanoZ <edu.ZVanoZ@gmail.com>
It seems "laminas-db" is abandoned.
| QA            | yes
Added questions for analisis.
=> add "Is “laminas-db” abandoned?"

meetings/minutes/2022-02-07-TSC-Minutes.md
| QA            | yes
* fix the date in the heading
* apply code style/links
* apparently, Americans can't handle German umlauts :)
=> Fix some typos in 2022-02-07 Minutes

meetings/agenda.md, meetings/minutes/2022-03-07-TSC-Minutes.md
Minutes from the 2022-03-07 meeting, and a refresh of the agenda for April 2022.
=> Meeting minutes for 2022-03-07

meetings/agenda.md
/cc @gsteel
/cc @internalsystemerror
Signed-off-by: Marco Pivetta <ocramius@gmail.com>
| Documentation | no
| New Feature   | yes?
| QA            | yes
=> Proposing George Steel and Gary Lockett as new TSC members

meetings/agenda.md
Signed-off-by: Andreas Heigl <heiglandreas@users.noreply.github.com>
Add feedback to currently open issues to the agenda of the August TSC-meeting
=> Add short feedback to open issues

meetings/agenda.md
Signed-off-by: Geert Eltink <9497586+geerteltink@users.noreply.github.com>
=> Add coding style major release

meetings/agenda.md
We have our first application for the commercial vendor program; I've added an item to the agenda to discuss and vote.
=> CVP application: DotKernel

meetings/agenda.md
Proposed issues for the agenda:
- Default git branching on new majors
- Security only packages and dependency updates
=> Proposed agenda items

meetings/agenda.md, meetings/minutes/2022-09-12-TSC-Minutes.md
- Provides minutes for the 2022-09-12 TSC meeting
- Resets the agenda for the 2022-10-03 TSC meeting
=> 2022-09-12 TSC meeting minutes

meetings/agenda.md
https://github.com/laminas/laminas-filter/issues/79
https://github.com/laminas/laminas-filter/pull/78
=> Propose filter compression adapter deprecations

meetings/agenda.md, meetings/minutes/2022-09-12-TSC-Minutes.md, meetings/minutes/2022-11-07-TSC-Minutes.md
- Fixes a date reference in the September 2022 minutes
- Adds minutes for the 2022-11-07 meeting
- Resets the agenda for the 2022-12-04 meeting
=> Minutes for the 2022-11-07 meeting 

meetings/agenda.md, meetings/minutes/2023--1-09-TSC-Minutes.md
Provides minutes for the 2023-01-09 TSC meeting, and resets the agenda for the upcoming 2023-03-06 TSC meeting.
=> Minutes for the 2023-01-09 TSC meeting

meetings/agenda.md
=> Add Dotkernel API proposal idea

meetings/agenda.md, meetings/minutes/2023-03-06-TSC-Minutes.md
- Meeting minutes from 2023-03-06 TSC meeting
- Agenda refresh
=> 2022-03-06 meeting minutes

meetings/agenda.md
DotKernel's TSC meeting agenda for the 3rd of April, 2023
=> DotKernel's TSC meeting agenda for the 3rd of April, 2023

meetings/minutes/2023-04-03-TSC-Minutes.md
Minutes from the 2023-04-03 TSC meeting.
=> Minutes fromt he 2023-04-03 TSC meeting

meetings/agenda.md
This PR:
- Updates the date of the next meeting
- Removes the agenda items from the previous meeting
- Adds an agenda item for the next meeting
=> Update the meeting agenda for the next meeting

meetings/agenda.md, meetings/minutes/2023-05-08-TSC-Minutes.md
- Add minutes from 2023-05-08 TSC meeting
- Refresh agenda
=> Add minutes from May meeting

meetings/agenda.md, meetings/minutes/2023-05-08-TSC-Minutes.md
This PR adds a topic to the agenda to discuss adding https://github.com/rectorphp/rector to our workflow.
Requires:
- https://github.com/laminas/technical-steering-committee/pull/144
=> Add a discussion of adding rector to our workflow to the agenda

meetings/agenda.md
Proposed topics for next meeting:
- laminas-psr7-serializer
- laminas-api-tools and Renovate
=> Proposed topics for 2023-08-07 meeting

meetings/agenda.md
Agenda is not yet moved to minutes, so we might want to wait with merging until the agenda is reset.
=> agenda: PHP 8.3 compatibility

meetings/agenda.md, meetings/minutes/2023-10-02-TSC-Minutes.md
- Minutes from today's meeting
- Reset of agenda
=> 2023-10-02 TSC meeting minutes

meetings/agenda.md
Ref https://github.com/laminas/laminas-crypt/pull/32
=> Add abandonment of laminas-crypt to the agenda

meetings/agenda.md
I believe this may have been discussed in Slack at some point as I couldn't find any information about it in any past meeting minutes.
Sorry if this ends up being a duplicate of discussion elsewhere.
=> Abandon `laminas-twitter`

meetings/agenda.md, meetings/minutes/2023-11-06-TSC-Minutes.md
- Adds minutes for the 2023-11-06 meeting
- Resets the agenda for the next meeting
=> 2023-11-06 meeting minutes

meetings/minutes/2021-05-03-TSC-Minutes.md, meetings/minutes/2021-12-06-TSC-Minutes.md, meetings/minutes/2023-11-06-TSC-Minutes.md
=> Corrects the spelling of a team member's last name

meetings/agenda.md
=> Add topic about laminas-pimple-config to agenda.

meetings/agenda.md, meetings/minutes/2023-12-04-TSC-Minutes.md
- Minutes from the 2023-12-04 meeting
- Agenda reset for next meeting: 2024-01-08!
=> 2023-12-04 TSC meeting minutes

meetings/agenda.md, meetings/minutes/2024-03-04-TSC-Minutes.md
- Adds minutes from 2024-03-04 meeting
- Resets agenda for April meeting
=> 2024-03-04 TSC Meeting minutes

meetings/agenda.md
Issues rised by Dotkernel Organisation
=> Update agenda.md for TSC May 2024

meetings/agenda.md, meetings/minutes/2024-05-06-TSC-Minutes.md
- Provides minutes from the meeting
- Refreshes the agenda for June 2024
=> 2024-05-06 TSC Meeting Minutes

meetings/agenda.md
- Fix incorrect meeting date
- Add link to translator repo for the 3rd agenda item
=> Amendments to agenda

meetings/agenda.md
=> Add agenda item to add @arhimede to the TSC

meetings/agenda.md
Meeting postponed, update 5th to 12th of August
=> Update agenda.md: update date to next week

meetings/agenda.md, meetings/minutes/2024-08-12-TSC-Minutes.md
- Provides minutes for the 2024-08-12 TSC meeting
- Resets the agenda for next meeting
=> 2024-08-12 TSC meeting minutes

meetings/agenda.md, meetings/minutes/2024-10-07-TSC-Minutes.md
- Minutes from the meeting
- Agenda reset for 2024-11-04 meeting
=> 2024-10-07 TSC meeting minutes

meetings/agenda.md
Added a proposal to the agenda to consider financing a new version of Matthew Setter's book "Mezzio Essentials."
=> Add discussion item for financing "Mezzio Essentials" book

meetings/agenda.md
Suggesting an agenda topic about a potential major release of `laminas-di` as discussed in the contributors channel.
=> Add agenda topic for laminas-di

meetings/agenda.md
The agenda was not reset after the November meeting
=> Reset agenda after November meeting

meetings/agenda.md
=> Add agenda item to discuss the release of mezzio-router v4

meetings/agenda.md
This PR proposes running through all open issues/PRs and close the stale ones we identify based on a set of criteria the committee agrees upon. The goal is to reduce the number of open issues/PRs so that work can be focused on the active ones.
=> Stale issue/PR cleanup proposal

meetings/agenda.md, meetings/minutes/2025-01-06-TSC-Minutes.md
Minutes from the meeting today.
=> 2025-01-06 Meeting minutes

meetings/agenda.md
=> Add agenda items for laminas-session major release and organisation email service provider

meetings/agenda.md
| Documentation | no
| New Feature   | yes
=> New design and layout

meetings/agenda.md
=> fix agenda formatting

meetings/minutes/2025-02-03-TSC-Minutes.md
=> added 2025-02-03 TSC minutes

meetings/minutes/2023-12-04-TSC-Minutes.md
Indicate what was done after TSC meeting
=> A follow up was done. Useful for everyone to know.

meetings/agenda.md, meetings/minutes/2025-03-03-TSC-Meeting.md
- Minutes from the meeting
- Reset of the agenda for April 2025 meeting
=> 2025-03-03 TSC meeting minutes

meetings/minutes/2025-03-03-TSC-Meeting.md
=> add async vote result

meetings/agenda.md
Maybe will have @weierophinney with us at this meeting :-)
=> Start agenda for September 2025 TSC meeting

meetings/agenda.md, meetings/minutes/2025-09-08-TSC-Minutes.md
=> Add minute for Sept 2025 TSC meeting
